[package]
name = "image-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5.20", features = ["derive"] }
image = { version = "0.25", features = ["avif-native"] }
